// Generated by CoffeeScript 1.4.0
var rideSearcher,
  __bind = function (fn, me) { return function () { return fn.apply(me, arguments); }; };

rideSearcher = rideSearcher || {};

require(['components/map-route', 'components/input/date-picker', 'components/input/text-input'], function (MapRoute, DatePicker, TextInput) {
  var RequestRideModal, RideSearcher, RouteRenderer, Trip;
  RideSearcher = (function () {

    function RideSearcher() {
      this.processResults = __bind(this.processResults, this);

      this.toJson = __bind(this.toJson, this);

      this.setButton = __bind(this.setButton, this);

      this.clearTrips = __bind(this.clearTrips, this);

      this.searchResults = __bind(this.searchResults, this);

      var _this = this;
      this.mapOptions = {
        center: [26.489000, 80.300000],
        zoom: 13
      };
      this.map = L.map('map_canvas', this.mapOptions);
      L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '© OpenStreetMap contributors'
      }).addTo(this.map);
      this.womenOnly = $('#search-women-only');
      this.departure = new DatePicker($('#search-departure'), $('#search-departure-date'), false);
      this.route = new MapRoute($('#search-route'), this.map, $('#search-from'), $('#search-to'));
      this.searchButton = $('#search-button');
      this.searchButton.click(function () {
        var data;
        if (_this.searchButton.hasClass('disabled')) {
          return null;
        }
        data = _this.toJson();
        if (data === null) {
          return null;
        }
        console.log(data);
        _this.setButton('btn btn-primary disabled', 'Searching...');
        return $.ajax({
          url: '/search_ajax.php',
          type: 'GET',
          data: {
            'data': JSON.stringify(data)
          },
          success: _this.searchResults,
          complete: function (xhr, status) {
            if (status !== 'success') {
              return _this.setButton('btn btn-danger', "" + xhr.statusText);
            }
          }
        });
      });
      this.trips = $('#trips');
      this.requestModal = new RequestRideModal();
    }

    RideSearcher.prototype.searchResults = function (data) {
      var error, json;
      console.log(data);
      error = 'Unknown Error!';
      json = JSON.parse(data);
      if (json) {
        if (json['status'] === 'OK') {
          this.clearTrips();
          if (json['trips'].length === 0) {
            this.setButton('btn btn-primary', 'No trips found');
          } else {
            this.processResults(json['trips']);
            this.setButton('btn btn-primary', 'Search');
          }
          return;
        } else {
          error = json['msg'];
        }
      }
      return this.setButton('btn btn-danger', error);
    };

    RideSearcher.prototype.clearTrips = function () {
      return this.trips.html('');
    };

    RideSearcher.prototype.setButton = function (btnClass, msg) {
      this.searchButton.attr('class', btnClass);
      return this.searchButton.html("<i class='icon icon-white icon-search'></i> " + msg);
    };

    RideSearcher.prototype.toJson = function () {
      var json;
      json = {
        departure: this.departure.getTime(),
        women_only: this.womenOnly.prop('checked'),
        route: this.route.toJson()
      };
      if (json['route'] === null || json['women_only'] === null) {
        return null;
      }
      return json;
    };

    RideSearcher.prototype.processResults = function (tripsData) {
      var id, tripData, _i, _len;
      this.trips.hide();

      // Clean up previous routes
      if (this.tripsTable) {
        for (var key in this.tripsTable) {
          if (this.tripsTable[key] && this.tripsTable[key].routeRenderer) {
            this.tripsTable[key].routeRenderer.remove();
          }
        }
      }

      this.tripsTable = {};
      for (_i = 0, _len = tripsData.length; _i < _len; _i++) {
        tripData = tripsData[_i];
        id = tripData.id;
        this.tripsTable[id] = new Trip(this.trips, this.map, this.requestModal, tripData);
      }
      return this.trips.slideDown(1000);
    };

    return RideSearcher;

  })();
  Trip = (function () {

    function Trip(container, map, modal, data) {
      this.container = container;
      this.map = map;
      this.modal = modal;
      this.data = data;
      this.updateStatus = __bind(this.updateStatus, this);

      this.requestRide = __bind(this.requestRide, this);

      this.setButton = __bind(this.setButton, this);

      this.tripTemplate = _.template($('#trip-template').html());
      this.data.departure_string = (new Date(parseInt(this.data.departure_time) * 1000)).toLocaleString();
      this.container.append(this.tripTemplate(this.data));
      this.routeRenderer = new RouteRenderer(this.map, this.data);
      $("#trip-" + this.data.id).hover(this.routeRenderer.hoverIn, this.routeRenderer.hoverOut);
      this.requestButton = $("#request-trip-" + this.data.id);
      this.requestButton.click(this.requestRide);
      this.updateStatus();
    }

    Trip.prototype.setButton = function (btnClass, text) {
      this.requestButton.attr('class', "btn btn-small " + btnClass);
      return this.requestButton.html("<i class='icon icon-envelope icon-white'></i> " + text);
    };

    Trip.prototype.requestRide = function (e) {
      if (this.requestButton.hasClass('disabled')) {
        return;
      }
      if ($('#logged-in').length === 0) {
        return this.setButton('btn-danger', 'Login Required!');
      }
      this.modal.reset();
      this.modal.load(this);
      return this.modal.show();
    };

    Trip.prototype.updateStatus = function () {
      if (this.data.status === null) {
        return this.setButton('btn-primary', 'Request Ride');
      } else if (this.data.status === 'PENDING') {
        return this.setButton('btn-info disabled', 'Request Pending');
      } else if (this.data.status === 'DECLINED') {
        return this.setButton('btn-danger disabled', 'Request Declined');
      } else if (this.data.status === 'APPROVED') {
        return this.setButton('btn-success disabled', 'Request Approved');
      }
    };

    return Trip;

  })();

  RouteRenderer = (function () {

    function RouteRenderer(map, route) {
      this.map = map;
      this.route = route;
      this.hoverIn = __bind(this.hoverIn, this);
      this.hoverOut = __bind(this.hoverOut, this);

      // Initialize routing control without markers
      this.routingControl = L.Routing.control({
        router: L.Routing.osrmv1({
          serviceUrl: 'https://router.project-osrm.org/route/v1',
          profile: 'driving'
        }),
        waypoints: [
          L.latLng(this.route.origin.lat, this.route.origin.lon),
          L.latLng(this.route.destination.lat, this.route.destination.lon)
        ],
        fitSelectedRoutes: false,
        show: false,
        createMarker: function () { return null; }, // Disable markers
        lineOptions: {
          styles: [
            { color: '#3388ff', opacity: 0.0, weight: 6 },
            { color: '#ffffff', opacity: 0.0, weight: 4 }
          ]
        }
      });

      this.routingControl.addTo(this.map);
    }

    RouteRenderer.prototype.hoverIn = function (e) {
      if (this.routingControl) {
        this.routingControl.setStyle({
          styles: [
            { color: '#3388ff', opacity: 0.8, weight: 6 },
            { color: '#ffffff', opacity: 0.3, weight: 4 }
          ]
        });
      }
    };

    RouteRenderer.prototype.hoverOut = function (e) {
      if (this.routingControl) {
        this.routingControl.setStyle({
          styles: [
            { color: '#3388ff', opacity: 0.0, weight: 6 },
            { color: '#ffffff', opacity: 0.0, weight: 4 }
          ]
        });
      }
    };

    RouteRenderer.prototype.remove = function () {
      if (this.routingControl) {
        this.map.removeControl(this.routingControl);
      }
    };

    return RouteRenderer;

  })();

  RequestRideModal = (function () {

    function RequestRideModal() {
      this.setButton = __bind(this.setButton, this);

      this.submit = __bind(this.submit, this);

      this.toJson = __bind(this.toJson, this);

      this.reset = __bind(this.reset, this);

      this.hide = __bind(this.hide, this);

      this.show = __bind(this.show, this);

      this.load = __bind(this.load, this);
      this.el = $('#modal-request-ride');
      this.info = $('#modal-trip-info');
      this.requestMessage = new TextInput($('#modal-trip-request-message').parent().parent(), $('#modal-trip-request-message'));
      this.submitButton = $('#modal-request-ride-submit');
      this.submitButton.click(this.submit);
      this.tripTemplate = _.template($('#trip-modal-template').html());
    }

    RequestRideModal.prototype.load = function (trip) {
      this.trip = trip;
      return this.info.append(this.tripTemplate(this.trip.data));
    };

    RequestRideModal.prototype.show = function () {
      return this.el.modal('show');
    };

    RequestRideModal.prototype.hide = function () {
      return this.el.modal('hide');
    };

    RequestRideModal.prototype.reset = function () {
      this.info.html('');
      return this.setButton('btn btn-primary', 'Request');
    };

    RequestRideModal.prototype.toJson = function () {
      return {
        'message': this.requestMessage.getValue(),
        'trip_id': this.trip.data.id
      };
    };

    RequestRideModal.prototype.submit = function (e) {
      var data,
        _this = this;
      data = this.toJson();
      return $.ajax({
        url: '/search_ajax.php',
        type: 'POST',
        data: {
          'data': JSON.stringify(data)
        },
        success: function (data) {
          var json;
          console.log(data);
          json = JSON.parse(data);
          if (!json) {
            _this.setButton('btn btn-danger', 'Unknown error!');
            return;
          }
          if (json['status'] === 'OK') {
            _this.hide();
            _this.reset();
            _this.trip.data.status = 'PENDING';
            return _this.trip.update
            Status();
          } else {
            return _this.setButton('btn btn-danger', json['msg']);
          }
        },
        error: function (data) {
          return this.setButton('btn btn-danger', 'Unknown error!');
        }
      });
    };

    RequestRideModal.prototype.setButton = function (btnClass, msg) {
      this.submitButton.attr('class', btnClass);
      return this.submitButton.html("<i class='icon icon-white icon-search'></i> " + msg);
    };

    return RequestRideModal;

  })();
  return rideSearcher = new RideSearcher();
});